### ISSUE TITLE
Satoshi limit for BCY network

### ISSUE THREAD

**Issue by mikejm1002** [blockcypher/blockcypher-python#102]
`{'error': 'Error building faucet transaction: Not enough funds in 1 inputs to pay for 1 outputs, missing -979305..'}`

Why am I getting this error? The documentation says the limit is atleast 10 million satoshis but I am only trying a transaction under 1 million satoshis: https://www.blockcypher.com/dev/bitcoin/#testing
`On the BlockCypher Test Chain, the faucet will refuse to fund an address with more than 500 billion BlockCypher satoshis and will not fund more than 100 million BlockCypher satoshis at a time. On Bitcoin Testnet3 those numbers are adjusted to 10 million and 500,000 testnet satoshis respectively.`

**Comment by mikejm1002** [comment]
BCY


Michael McClelland

Full Stack Developer

Bluestone Analytics

571.424.9405

Fairfax, VA

***@***.***

bluestoneanalytics.com

________________________________

**Comment by quentinlesceller** [comment]
I've answered on our support channel. Closing.
