### ISSUE TITLE
The api is not finding all uxto from an specific address in testnet env.

### ISSUE THREAD

**Issue by pinhopro** [blockcypher/blockcypher-python#25]
this is not an issue with the python wrapper, but it is an issue with the  https://api.blockcypher.com/v1/btc/test3/txs/new api endpoint 

Here is how to reproduce 
https://gist.github.com/pinhopro/43a01f3aa63c8e25acfa

**Comment by matthieu** [comment]
Hey Rodrigo, thanks for the nice gist to reproduce!

Looking at the underlying data on mjyQdm4k9W9wqgx816AXM6tVWZqrRZWsjQ (I think that's the address for your private key) I'm not sure I fully follow. Right now that address has a 0 balance and no confirmed UTXOs exists. Looking at the transactions you listed in your gist, neither e7369... nor 8df5a... impact that address. Only c0e99... does and it's been spent already. I've also double-checked with other sources of data and it all checks.

Am I missing something?

**Comment by pinhopro** [comment]
mjyQdm4k9W9wqgx816AXM6tVWZqrRZWsjQ  is just an address that I am sending transactions too.

the address on the private key 91uWRwt2mXZRB6TisAt9iFfhezZemTNbga5S3UFJqbPJFZFNRPv is mfoxXHwZ6kjoznatZSCzZw8XivGWWJ6fzv   ) 

https://api.blockcypher.com/v1/btc/test3/addrs/mfoxXHwZ6kjoznatZSCzZw8XivGWWJ6fzv?unspentOnly=true

**Comment by matthieu** [comment]
Okay, that makes more sense. Ended up being some unusual corner case in UTXO selection due to how this address is structured. Fixed it in the API, should be better now. Thanks again for the test case!

**Comment by pinhopro** [comment]
works like a charm :)
