### ISSUE TITLE
Add new flags for Confidence changes

### ISSUE THREAD

**Issue by acityinohio** [blockcypher/blockcypher-python#44]
https://medium.com/blockcypher-blog/important-changes-to-blockcypher-s-confidence-api-7bbd283e099c

**Comment by mflaxman** [comment]
Good call, will add!

**Comment by acityinohio** [comment]
awesome, thanks @mflaxman!

**Comment by mflaxman** [comment]
Fixed in 864f2093147583a1ba4ad4f702bb8b82f4c38686 branched off of @acityinohio PR (thanks Josh!).
