### ISSUE TITLE
Why generate_address endpoint is not supported?

### ISSUE THREAD

**Issue by miratcan** [blockcypher/blockcypher-python#50]
I see that [generate address endpoint](http://dev.blockcypher.com/?python#generate-address-endpoint) is available for other programming languages.

**Comment by mflaxman** [comment]
Hi @miratcan , thanks for checking out the python library.

It's bad practice to generate an address server side when it can easily be done locally. Have you checked out https://github.com/sbuss/bitmerchant ?

```
>>> from bitmerchant.wallet import Wallet
>>> w = Wallet.new_random_wallet()
>>> w.to_address()
u'1FcGVUCRsKe9Q1mK9hmTFMn1iC9gKcqYY6'
>>> w.export_to_wif()
'L3Q7xCK3HPxLiJUuFVGYxcCVSJcah1EmoJE3Rey9tfj2VjmjSmho'
>>> w.get_private_key_hex()
'b8612b8705d78425a85d1778854c9c37c73fbe577c3774a52008f6894acea535'
>>> w.get_public_key_hex()
'02307c5f55ceecedc3eed1b6c8e64c29cef06209d7e8a3163fbd7d493528ba0a50'
```

**Comment by wizardofozzie** [comment]
I find bitmerchant has too many dependencies, especially since I primarily use the iOS Pythonista 2.0 app. I'd recommend [pybitcointools](https://github.com/vbuterin/pybitcointools) if this bitmerchant is too cumbersome:

```
>>> from bitcoin import *
>>> pk = privkey_hex = random_key()
>>> privkey_wif = encode_privkey(pk, "wif")
>>> pubkey = privtopub(pk)
>>> addr = pubtoaddr(pk)
>>> print addr
```

**Comment by miratcan** [comment]
> It's bad practice to generate an address server side when it can easily be done locally. Have you checked out https://github.com/sbuss/bitmerchant ?

But on other programming languages there's support for generating address inside blockcypher library. For example on ruby we can create address by calling:

    > block_cypher.address_generate
    => {"private"=>"39c8788ef9815d061a2a4528817b3c23730b1129e5ca60032138061f35483951",
          "public"=>"039dc801dd76a7fa03789e0fe8efdd7e0857e73fa4ae38a294a60002ef949e83c4",
          "address"=>"1FdQDEnHXibwMMMKaaNGrhrcujJNZyszUN",
          "wif"=>"KyA2uUUMZkiRcSTx3PE1pBeMFgyifpxswcJu3Q7fVwXXZmvh48JA"}

Don't you think that it's inconsistent support?

> Hi @miratcan , thanks for checking out the python library.
Thanks for your response :) :+1:

**Comment by mflaxman** [comment]
@miratcan I'm not an employee of blockcypher!

I think there are good uses for them building that feature into the API (BTC testnet and blockcypher testnet are great for example), but I really don't think people should be using that feature with real coin unless they have a very deep understanding of the protocol and know what they're doing. Fair exceptions would be things like a private key that is only going to touch 0.01 BTC and only for a matter of minutes, or if you're working in an obscure language that doesn't have a bitcoin address generation library (not sure there are any left at this point). So I think there are both reasons for them to include the feature and for me to not support it in the python library.

Does that make sense?
