### ISSUE TITLE
Generating address in  python

### ISSUE THREAD

**Issue by singhprabhanshu** [blockcypher/blockcypher-python#57]
Genrating address in python gives the warning with the response. is it right to use the response address for further processing? The api and response is given below:

blockcypher.generate_new_address(api_key='b68a3087d11b4285b041564d26bda061')

Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.

{u'wif': u'L2fVHT7uz8ZnWcopKTeQouyHXds6tGfMVmdA5Tt2aYE2efMxq2EY', u'public': u'03b8f098fc3ceb9151cfc8971e6f68b033a3b4043712facb0d4fbe984d5febe9f9', u'private': u'a272acc0f2da51c18c6968007e73a27c20c1ab96ef2bbe7f07f11bd074e1d570', u'address': u'14cMjecEj97tNP3mV6rGQA3hMN7fCgvSyL'}

can i use the addresses for transaction and  web hooking?

**Comment by quentinlesceller** [comment]
See warning here https://www.blockcypher.com/dev/bitcoin/#generate-address-endpoint.
