### ISSUE TITLE
Wrong assertion value for BTC address length

### ISSUE THREAD

**Issue by reijin90** [blockcypher/blockcypher-python#63]
The assertion for wallet_name is wrong in my opinion as it checks if the wallet has a length of 25 characters whereas currently a BTC address has a length of 35 characters. Is this a typo?
> def get_wallet_balance(wallet_name, api_key, omit_addresses=False, coin_symbol='btc'):
>     assert is_valid_coin_symbol(coin_symbol)
>     assert api_key
>     assert len(wallet_name) <= 25, wallet_name

**Comment by quentinlesceller** [comment]
Wallet name is different from btc address. See doc https://www.blockcypher.com/dev/bitcoin/#wallet-api.
