### ISSUE TITLE
Litecoin Segwit Addresses not supported

### ISSUE THREAD

**Issue by page1** [blockcypher/blockcypher-python#70]
It seems I have to convert my litecoin segwit addresses through https://litecoin-project.github.io/p2sh-convert/ in order to make them work with this library. This is sub optimal.

**Comment by cal5k** [comment]
Seconded on this one. Litecoin SegWit addresses have been around for some time.

**Comment by quentinlesceller** [comment]
Indeed we are working on it and should be fixed very soon.

**Comment by quentinlesceller** [comment]
However considering that's an issue on BlockCypher side and not blockcypher-python I'm closing this issue.
