### ISSUE TITLE
Error in embed_data function. 

### ISSUE THREAD

**Issue by mevangelista-alvarado** [blockcypher/blockcypher-python#71]
From your API documentation, I tested the following script:
```
# Embedding String Data
>>> from blockcypher import embed_data
>>> embed_data(to_embed='I am the walrus', api_key='YOUR_TOKEN', data_is_hex=False)
{
  "data": "I am the walrus",
  "encoding": "string",
  "token": "YOUR_TOKEN",
  "hash": "cb6974e0fd57c91b70403e85ef48c840eecdca4804dfc4897b1321d5328e4f18"
} 
```
which is supposed to only add my BlockCypher token but i'm obtaining the following error message 
```
{'error': 'Server error while building the data transaction. Please contact support. Not enough
 funds after fees in 0 inputs to pay for 1 outputs, missing -3700.'}
```
 I do not understand why I lack funds if I'm only using my Blockcypher token. Thank you. 

I use Python 3.7 and 2.7

**Comment by quentinlesceller** [comment]
Closing this PR due to lack of activity. Please open a new one if you feel this is still relevant.
