### ISSUE TITLE
"UnicodeError: label too long" 

### ISSUE THREAD

**Issue by Davide3i** [blockcypher/blockcypher-python#79]
Launching a simple 
`get_address_overview('1BTCorgHwCg6u2YSAWKgS17qUad6kHmtQW')) `
triggers this exception. Has anyone encoutered this issue yet? I'm using Python 3.7/3.8.

>  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\encodings\idna.py", line 167, in encode
>     raise UnicodeError("label too long")
> UnicodeError: label too long

**Comment by MarcelBeining** [comment]
encountered this too, has too do with the idna encoding rules (address is too long for idna encoding)... any idea how to solve that? makes blockcypher api unusable

**Comment by quentinlesceller** [comment]
Taking a look at this now.

**Comment by MarcelBeining** [comment]
I found, that everything works if the url you are creating does contain slashes (/) instead of double-backslashes (\\).

**Comment by quentinlesceller** [comment]
I don't see any error on Linux and macOS.

**Comment by quentinlesceller** [comment]
Can reproduce on Windows. Unfortunately it seems like a Python issue which is still unresolved: https://bugs.python.org/issue32958

**Comment by quentinlesceller** [comment]
Okay nevermind found the issue.

**Comment by Davide3i** [comment]
Perfect, thank you.

**Comment by Davide3i** [comment]
This fix hasn't been pulled to PyPI yet.
