### ISSUE TITLE
Getting Assertion error

### ISSUE THREAD

**Issue by jaysea** [blockcypher/blockcypher-python#9]
Im getting an assertion error when I try most of the functions. In python 2.7.6

    blockcypher.get_num_confirmed_transactions('1BTCorgHwCg6u2YSAWKgS17qUad6kHmtQW')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/JC/src/blockcypher/blockcypher/api.py", line 202, in get_num_confirmed_transactions
        coin_symbol=coin_symbol)['n_tx']
      File "/Users/JC/src/blockcypher/blockcypher/api.py", line 154, in get_address_overview
        coin_symbol=coin_symbol)
    AssertionError

**Comment by mflaxman** [comment]
Sorry about that @jaysea! This isn't a problem when running modern python 3 but effects legacy python 2.

I'm working on a large branch right now and once I merge that in I'll add legacy python support. In the meantime, I recommend upgrading to python 3 anyway.

**Comment by mflaxman** [comment]
@jaysea this has been merged into master so if you'd like to try again it should work on python2 now. Sorry about that!
